import '/app/app_restful.dart';
import '../api_builder/api_model_constructor.dart';
import 'dart:html';

class CollectionBuilder {
  static Future<void> buildApiClass() async {
    String className = AppRestFull().appName;
    Map<String, Type> fields = await ApiConstructor().createCollection();

    final classCode = _generateClassCode(className, fields);
    _writeToFile(className, classCode);
    print('Class generated successfully!');
  }

  static String _generateClassCode(String className, Map<String, Type> fields) {
    final fieldDeclarations = fields.entries.map((entry) {
      final paramName = entry.key;
      final typeName = entry.value.toString();
      return '$typeName $paramName;';
    }).join('\n');

    final constructorParams = fields.keys.join(', ');

    final constructorAssignments = fields.keys
        .map((paramName) => 'this.$paramName = $paramName;')
        .join('\n');

    final fromJsonMethod = _generateFromJsonMethod(className, fields);
    final toJsonMethod = _generateToJsonMethod(className, fields);

    return '''
      class $className {
        $fieldDeclarations

        $className($constructorParams) {
          $constructorAssignments
        }

        $fromJsonMethod

        $toJsonMethod
      }
    ''';
  }

  static String _generateFromJsonMethod(
      String className, Map<String, Type> fields) {
    final parameters =
        fields.keys.map((paramName) => 'json["$paramName"]').join(', ');

    final assignments = fields.keys.map((paramName) {
      final typeName = fields[paramName].toString();
      return 'this.$paramName = json["$paramName"] as $typeName;';
    }).join('\n');

    return '''
      factory $className.fromJson(Map<String, dynamic> json) {
        return $className($parameters)
          .._fromJson(json);
      }

      void _fromJson(Map<String, dynamic> json) {
        $assignments
      }
    ''';
  }

  static String _generateToJsonMethod(
      String className, Map<String, Type> fields) {
    final toJsonFields = fields.keys
        .map((paramName) => '"$paramName": this.$paramName')
        .join(', ');

    return '''
      Map<String, dynamic> toJson() {
        return {
          $toJsonFields
        };
      }
    ''';
  }

  static void _writeToFile(String className, String classCode) {
    final blob = Blob([classCode], 'text/plain', 'native');
    final url = Url.createObjectUrlFromBlob(blob);
    final anchor = AnchorElement()
      ..href = url
      ..download = '${className}AutoGeneratedModel.dart'
      ..click();
    Url.revokeObjectUrl(url);
    print('File created successfully!');
  }
}
